### PR TITLE
History - Process Instance and Variable Instance

### PR DESCRIPTION
**Pull request by sinhashubham95**

### CODE REVIEW

**Comment by sinhashubham95** [comment]
@liderman can you check this PR? I have added the implementations for history process and variable instance. Also made a few fixes in the external task.

**Review by liderman — APPROVED** [review]
All OK.
Later I will make a PR to replace "*[]string" with "[]string".
There is no point in using a pointer to slice.

**Comment by sinhashubham95** [comment]
Yeah @liderman I thought of making that change as well, but that will result in a lot of changes. If you want we can connect once and can quickly get this done and a few other refactoring also I had in mind.

**Comment by liderman** [comment]
@sinhashubham95 Ok. I was planning to release a major release "v3.0.0". Using go modules makes it safe.
I made a PR with the changes:
https://github.com/citilinkru/camunda-client-go/pull/33
If you want to make backward incompatible changes, you can submit a PR.
Let me know when you need to release "v3.0.0" and I'll tag it.

**Comment by sinhashubham95** [comment]
@liderman I also had changes to use context in mind. Give me some time mostly by the next weekend or the one after that I will make all the changes.

**Comment by liderman** [comment]
@sinhashubham95 Ok. No problem.
Thanks.

**Pull request merged**
